import type { InvitationDocument, TextLayerProps, CanvasBackground } from './types';

// ── Default background ──

export const DEFAULT_BACKGROUND: CanvasBackground = {
  color: '#fffaf5',
  pattern: 'none',
};

// ── Default sample wedding invitation (email format: 600×800) ──

export const DEFAULT_INVITATION: InvitationDocument = {
  canvas: {
    width: 600,
    height: 800,
    background: DEFAULT_BACKGROUND,
  },
  layers: [
    // Corner ornaments — top-left flower
    {
      id: 'corner-tl',
      type: 'text',
      x: 48,
      y: 48,
      width: 48,
      height: 48,
      rotation: 0,
      zIndex: 1,
      opacity: 1,
      props: {
        content: '\u2766',
        fontSize: 36,
        fontFamily: 'var(--font-heading), Georgia, serif',
        weight: 400,
        color: '#b8925a',
        align: 'center',
        lineHeight: 1,
        letterSpacing: 0,
      } satisfies TextLayerProps,
    },
    // Corner ornaments — top-right flower
    {
      id: 'corner-tr',
      type: 'text',
      x: 504,
      y: 48,
      width: 48,
      height: 48,
      rotation: 0,
      zIndex: 1,
      opacity: 1,
      props: {
        content: '\u2766',
        fontSize: 36,
        fontFamily: 'var(--font-heading), Georgia, serif',
        weight: 400,
        color: '#b8925a',
        align: 'center',
        lineHeight: 1,
        letterSpacing: 0,
      } satisfies TextLayerProps,
    },
    // Corner ornaments — bottom-left flower
    {
      id: 'corner-bl',
      type: 'text',
      x: 48,
      y: 704,
      width: 48,
      height: 48,
      rotation: 0,
      zIndex: 1,
      opacity: 1,
      props: {
        content: '\u2766',
        fontSize: 36,
        fontFamily: 'var(--font-heading), Georgia, serif',
        weight: 400,
        color: '#b8925a',
        align: 'center',
        lineHeight: 1,
        letterSpacing: 0,
      } satisfies TextLayerProps,
    },
    // Corner ornaments — bottom-right flower
    {
      id: 'corner-br',
      type: 'text',
      x: 504,
      y: 704,
      width: 48,
      height: 48,
      rotation: 0,
      zIndex: 1,
      opacity: 1,
      props: {
        content: '\u2766',
        fontSize: 36,
        fontFamily: 'var(--font-heading), Georgia, serif',
        weight: 400,
        color: '#b8925a',
        align: 'center',
        lineHeight: 1,
        letterSpacing: 0,
      } satisfies TextLayerProps,
    },
    // Top rule line
    {
      id: 'rule-top',
      type: 'text',
      x: 160,
      y: 104,
      width: 280,
      height: 2,
      rotation: 0,
      zIndex: 1,
      opacity: 1,
      props: {
        content: '',
        fontSize: 0,
        fontFamily: 'var(--font-label), Inter, sans-serif',
        weight: 400,
        color: 'transparent',
        align: 'center',
        lineHeight: 0,
        letterSpacing: 0,
      } satisfies TextLayerProps,
    },
    // Eyebrow: "TOGETHER WITH THEIR FAMILIES"
    {
      id: 'eyebrow',
      type: 'text',
      x: 0,
      y: 144,
      width: 600,
      height: 30,
      rotation: 0,
      zIndex: 2,
      opacity: 1,
      props: {
        content: 'TOGETHER WITH THEIR FAMILIES',
        fontSize: 12,
        fontFamily: 'var(--font-label), Inter, sans-serif',
        weight: 400,
        color: '#8a8078',
        align: 'center',
        lineHeight: 1.6,
        letterSpacing: 4,
        textTransform: 'uppercase',
      } satisfies TextLayerProps,
    },
    // Names: "Amelia" (line 1)
    {
      id: 'name-amelia',
      type: 'text',
      x: 0,
      y: 280,
      width: 600,
      height: 60,
      rotation: 0,
      zIndex: 2,
      opacity: 1,
      props: {
        content: 'Amelia',
        fontSize: 52,
        fontFamily: 'var(--font-heading), Georgia, serif',
        weight: 400,
        color: '#3a3430',
        align: 'center',
        lineHeight: 1.1,
        letterSpacing: 0,
      } satisfies TextLayerProps,
    },
    // "& Jonathan" (line 2)
    {
      id: 'name-jonathan',
      type: 'text',
      x: 0,
      y: 350,
      width: 600,
      height: 60,
      rotation: 0,
      zIndex: 2,
      opacity: 1,
      props: {
        content: '& Jonathan',
        fontSize: 44,
        fontFamily: 'var(--font-heading), Georgia, serif',
        weight: 400,
        color: '#3a3430',
        align: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
      } satisfies TextLayerProps,
    },
    // Decorative divider between names and invite line
    {
      id: 'divider',
      type: 'text',
      x: 130,
      y: 445,
      width: 340,
      height: 24,
      rotation: 0,
      zIndex: 1,
      opacity: 1,
      props: {
        content: '\u2500  \u2665  \u2500',
        fontSize: 16,
        fontFamily: 'var(--font-heading), Georgia, serif',
        weight: 400,
        color: '#b8925a',
        align: 'center',
        lineHeight: 1,
        letterSpacing: 0,
      } satisfies TextLayerProps,
    },
    // Invitation line
    {
      id: 'invite-line',
      type: 'text',
      x: 0,
      y: 500,
      width: 600,
      height: 30,
      rotation: 0,
      zIndex: 2,
      opacity: 1,
      props: {
        content: 'INVITE YOU TO CELEBRATE THEIR WEDDING',
        fontSize: 12,
        fontFamily: 'var(--font-label), Inter, sans-serif',
        weight: 500,
        color: '#8a8078',
        align: 'center',
        lineHeight: 1.6,
        letterSpacing: 3,
        textTransform: 'uppercase',
      } satisfies TextLayerProps,
    },
    // Date
    {
      id: 'date',
      type: 'text',
      x: 0,
      y: 555,
      width: 600,
      height: 30,
      rotation: 0,
      zIndex: 2,
      opacity: 1,
      props: {
        content: 'SATURDAY  \u00B7  24 MAY 2027  \u00B7  3:00 PM',
        fontSize: 13,
        fontFamily: 'var(--font-label), Inter, sans-serif',
        weight: 500,
        color: '#3a3430',
        align: 'center',
        lineHeight: 1.6,
        letterSpacing: 2,
        textTransform: 'uppercase',
      } satisfies TextLayerProps,
    },
    // Bottom rule
    {
      id: 'rule-bottom',
      type: 'text',
      x: 160,
      y: 605,
      width: 280,
      height: 2,
      rotation: 0,
      zIndex: 1,
      opacity: 1,
      props: {
        content: '',
        fontSize: 0,
        fontFamily: 'var(--font-label), Inter, sans-serif',
        weight: 400,
        color: 'transparent',
        align: 'center',
        lineHeight: 0,
        letterSpacing: 0,
      } satisfies TextLayerProps,
    },
    // Venue name
    {
      id: 'venue-name',
      type: 'text',
      x: 0,
      y: 630,
      width: 600,
      height: 32,
      rotation: 0,
      zIndex: 2,
      opacity: 1,
      props: {
        content: 'The Garden Pavilion',
        fontSize: 22,
        fontFamily: 'var(--font-heading), Georgia, serif',
        weight: 400,
        color: '#3a3430',
        align: 'center',
        lineHeight: 1.3,
        letterSpacing: 0,
      } satisfies TextLayerProps,
    },
    // Venue location
    {
      id: 'venue-location',
      type: 'text',
      x: 0,
      y: 672,
      width: 600,
      height: 24,
      rotation: 0,
      zIndex: 2,
      opacity: 1,
      props: {
        content: 'Cotswolds, England',
        fontSize: 13,
        fontFamily: 'var(--font-label), Inter, sans-serif',
        weight: 400,
        color: '#8a8078',
        align: 'center',
        lineHeight: 1.6,
        letterSpacing: 1.5,
        textTransform: 'uppercase',
      } satisfies TextLayerProps,
    },
    // Bottom accent: small decorative cluster
    {
      id: 'accent-bottom',
      type: 'text',
      x: 200,
      y: 720,
      width: 200,
      height: 40,
      rotation: 0,
      zIndex: 1,
      opacity: 1,
      props: {
        content: '\u2726   \u2726   \u2726',
        fontSize: 16,
        fontFamily: 'var(--font-heading), Georgia, serif',
        weight: 400,
        color: '#b8925a',
        align: 'center',
        lineHeight: 1,
        letterSpacing: 0,
      } satisfies TextLayerProps,
    },
  ],
};