import type { DemoFaq, DemoGuestQuestion, DemoQuestionActivity, DemoPortalSettings } from './demoTypes';
import { DEMO_CONFIG } from './demoConfig';

export const demoPortalSettings: DemoPortalSettings = {
  show_questions: true,
  allow_guest_questions: true,
  questions_contact_message: 'We\'ll do our best to get back to you within 48 hours. For urgent matters, please contact the wedding coordinator.',
  questions_response_time_message: 'We typically respond within 1-2 days.',
};

export const demoFaqs: DemoFaq[] = [
  {
    id: 'demo-faq-1',
    wedding_id: DEMO_CONFIG.weddingId,
    category: 'dress_code',
    question: 'What should I wear to the wedding?',
    answer: 'The dress code is formal garden party attire. Think cocktail dresses, smart jumpsuits, or a suit and tie. The ceremony is outdoors on grass, so maybe leave the stilettos at home — block heels or wedges will serve you much better.',
    related_links: [],
    is_published: true,
    status: 'published',
    sort_order: 1,
    helpful_count: 12,
    not_helpful_count: 1,
    created_at: '2027-04-01T10:00:00Z',
    updated_at: '2027-04-01T10:00:00Z',
  },
  {
    id: 'demo-faq-2',
    wedding_id: DEMO_CONFIG.weddingId,
    category: 'children',
    question: 'Can we bring our children?',
    answer: 'We love your little ones, but we\'ve decided to keep the ceremony and reception adults-only — with the exception of immediate family children named on the invitation. If you need help finding local childcare, the Sussex Nanny Agency comes highly recommended.',
    related_links: [
      { label: 'Sussex Nanny Agency', url: 'https://example.com/nanny', type: 'external' },
    ],
    is_published: true,
    status: 'published',
    sort_order: 2,
    helpful_count: 8,
    not_helpful_count: 3,
    created_at: '2027-04-02T10:00:00Z',
    updated_at: '2027-04-02T10:00:00Z',
  },
  {
    id: 'demo-faq-3',
    wedding_id: DEMO_CONFIG.weddingId,
    category: 'parking',
    question: 'Is there parking at the venue?',
    answer: 'Yes — The Orangery has a private car park with space for about 60 cars. It\'s a short walk from the car park to the ceremony garden. There are also a few accessible spaces right by the entrance. Overnight parking is allowed if you leave your car and collect it by 11am the next morning.',
    related_links: [],
    is_published: true,
    status: 'published',
    sort_order: 3,
    helpful_count: 15,
    not_helpful_count: 0,
    created_at: '2027-04-03T10:00:00Z',
    updated_at: '2027-04-03T10:00:00Z',
  },
  {
    id: 'demo-faq-4',
    wedding_id: DEMO_CONFIG.weddingId,
    category: 'travel',
    question: 'How do I get to the venue from London?',
    answer: 'The easiest route is to take a train from London Victoria to Haywards Heath (about 45 minutes), then grab a taxi for the final 15-minute ride. If you\'re driving, it\'s about 90 minutes from central London via the M23/A23. We\'ve arranged a shuttle bus from Haywards Heath station for guests staying at the recommended hotels — check the Travel section for the timetable.',
    related_links: [
      { label: 'Travel & accommodation', url: '/guest/travel', type: 'internal' },
    ],
    is_published: true,
    status: 'published',
    sort_order: 4,
    helpful_count: 20,
    not_helpful_count: 0,
    created_at: '2027-04-04T10:00:00Z',
    updated_at: '2027-04-04T10:00:00Z',
  },
  {
    id: 'demo-faq-5',
    wedding_id: DEMO_CONFIG.weddingId,
    category: 'timings',
    question: 'What time does everything start and finish?',
    answer: 'The ceremony starts at 2pm sharp — we recommend arriving by 1:30pm. Drinks and canapés follow from 2:45pm, the wedding breakfast is at 5pm, and the evening reception kicks off at 7:30pm with the first dance. Carriages at midnight.',
    related_links: [
      { label: 'Full itinerary', url: '/guest/itinerary', type: 'internal' },
    ],
    is_published: true,
    status: 'published',
    sort_order: 5,
    helpful_count: 25,
    not_helpful_count: 1,
    created_at: '2027-04-05T10:00:00Z',
    updated_at: '2027-04-05T10:00:00Z',
  },
  {
    id: 'demo-faq-6',
    wedding_id: DEMO_CONFIG.weddingId,
    category: 'gifts',
    question: 'Do you have a gift registry?',
    answer: 'Your presence at our wedding is the greatest gift of all. If you\'d like to contribute something more, we\'ve set up a honeymoon fund — you can find it in the Gift Registry section of the guest portal. Any contribution, however small, will help us create unforgettable memories in Japan.',
    related_links: [
      { label: 'Gift registry', url: '/guest/registry', type: 'internal' },
    ],
    is_published: true,
    status: 'published',
    sort_order: 6,
    helpful_count: 10,
    not_helpful_count: 2,
    created_at: '2027-04-06T10:00:00Z',
    updated_at: '2027-04-06T10:00:00Z',
  },
  {
    id: 'demo-faq-7',
    wedding_id: DEMO_CONFIG.weddingId,
    category: 'accommodation',
    question: 'Where should we stay?',
    answer: 'We\'ve arranged a block of rooms at The Birch Hotel in Haywards Heath and at the Spread Eagle in Midhurst. Both are about 15 minutes from the venue. Mention "Morris-Williams wedding" when booking for the discounted rate. Details and booking links are in the Travel section.',
    related_links: [
      { label: 'Accommodation options', url: '/guest/travel/accommodation', type: 'internal' },
    ],
    is_published: true,
    status: 'published',
    sort_order: 7,
    helpful_count: 18,
    not_helpful_count: 0,
    created_at: '2027-04-07T10:00:00Z',
    updated_at: '2027-04-07T10:00:00Z',
  },
  {
    id: 'demo-faq-8',
    wedding_id: DEMO_CONFIG.weddingId,
    category: 'food',
    question: 'I have a dietary requirement — who should I tell?',
    answer: 'Please include any dietary requirements or allergies when you RSVP. The venue\'s kitchen can accommodate most needs (vegetarian, vegan, gluten-free, nut allergies, etc.) — just give us the details and we\'ll make sure you\'re well looked after on the day.',
    related_links: [],
    is_published: false,
    status: 'draft',
    sort_order: 8,
    helpful_count: 0,
    not_helpful_count: 0,
    created_at: '2027-04-08T10:00:00Z',
    updated_at: '2027-04-08T10:00:00Z',
  },
];

export const demoGuestQuestions: DemoGuestQuestion[] = [
  {
    id: 'demo-gq-1',
    wedding_id: DEMO_CONFIG.weddingId,
    invitation_id: 'demo-inv-1',
    guest_id: 'demo-guest-1',
    category: 'travel',
    subject: 'Is there a shuttle from the hotel?',
    message: 'Hi both! We\'re staying at The Birch Hotel and were wondering if the shuttle bus stops there or if we need to make our own way to the venue? Thanks!',
    preferred_response_method: 'portal',
    status: 'answered',
    response: 'Yes — the shuttle will stop at The Birch Hotel at 1pm and 1:30pm on the day. Look for the Vowora-branded minibus in the car park. You don\'t need to book, just turn up!',
    responded_by: null,
    responded_at: '2027-05-10T14:30:00Z',
    created_at: '2027-05-09T09:15:00Z',
    updated_at: '2027-05-10T14:30:00Z',
  },
  {
    id: 'demo-gq-2',
    wedding_id: DEMO_CONFIG.weddingId,
    invitation_id: 'demo-inv-2',
    guest_id: 'demo-guest-3',
    category: 'food',
    subject: 'Nut allergy question',
    message: 'Just confirming — I mentioned my severe tree nut allergy in the RSVP. Will the kitchen be aware of this on the day? I carry an EpiPen but wanted to double-check.',
    preferred_response_method: 'email',
    status: 'answered',
    response: 'Absolutely — we\'ve flagged your allergy with the venue and the head chef has it on their list. All dishes served to you will be nut-free, and the kitchen takes cross-contamination very seriously. Please do bring your EpiPen just in case, but you should be in safe hands.',
    responded_by: null,
    responded_at: '2027-05-12T10:00:00Z',
    created_at: '2027-05-11T16:45:00Z',
    updated_at: '2027-05-12T10:00:00Z',
  },
  {
    id: 'demo-gq-3',
    wedding_id: DEMO_CONFIG.weddingId,
    invitation_id: 'demo-inv-3',
    guest_id: 'demo-guest-5',
    category: 'plus_ones',
    subject: 'Bringing my partner?',
    message: 'I know the invitation said just me, but my partner Tom can now make it — is there any chance he could come to the evening reception? Happy to pay for his meal if needed!',
    preferred_response_method: 'portal',
    status: 'pending',
    response: null,
    responded_by: null,
    responded_at: null,
    created_at: '2027-05-18T11:20:00Z',
    updated_at: '2027-05-18T11:20:00Z',
  },
  {
    id: 'demo-gq-4',
    wedding_id: DEMO_CONFIG.weddingId,
    invitation_id: 'demo-inv-4',
    guest_id: 'demo-guest-7',
    category: 'timings',
    subject: 'What time is the ceremony?',
    message: 'Sorry if this is somewhere obvious — I can\'t find the ceremony start time anywhere. Also, is there a backup plan if it rains?',
    preferred_response_method: 'either',
    status: 'pending',
    response: null,
    responded_by: null,
    responded_at: null,
    created_at: '2027-05-20T08:30:00Z',
    updated_at: '2027-05-20T08:30:00Z',
  },
  {
    id: 'demo-gq-5',
    wedding_id: DEMO_CONFIG.weddingId,
    invitation_id: 'demo-inv-1',
    guest_id: 'demo-guest-1',
    category: 'gifts',
    subject: 'Honeymoon fund vs physical gift',
    message: 'We\'d love to contribute to the honeymoon fund but also wanted to give you something physical to unwrap. Is there a way to do a small contribution plus bring a card on the day?',
    preferred_response_method: 'portal',
    status: 'closed',
    response: 'A card on the day would be lovely, and any contribution to the fund is completely optional — please don\'t feel you need to do both! We\'ll have a postbox for cards at the reception.',
    responded_by: null,
    responded_at: '2027-05-08T09:00:00Z',
    created_at: '2027-05-06T14:00:00Z',
    updated_at: '2027-05-08T09:00:00Z',
  },
];

export const demoQuestionActivity: DemoQuestionActivity[] = [
  {
    id: 'demo-qa-1',
    wedding_id: DEMO_CONFIG.weddingId,
    question_id: null,
    faq_id: 'demo-faq-1',
    invitation_id: 'demo-inv-1',
    guest_id: 'demo-guest-1',
    activity_type: 'helpful',
    metadata: {},
    created_at: '2027-05-01T10:00:00Z',
  },
  {
    id: 'demo-qa-2',
    wedding_id: DEMO_CONFIG.weddingId,
    question_id: null,
    faq_id: 'demo-faq-5',
    invitation_id: 'demo-inv-2',
    guest_id: 'demo-guest-3',
    activity_type: 'helpful',
    metadata: {},
    created_at: '2027-05-02T10:00:00Z',
  },
];