import type { DemoWedding, DemoWeddingVenue, DemoWeddingEvent, DemoEventAudience } from './demoTypes';
import { DEMO_CONFIG } from './demoConfig';

export const demoWedding: DemoWedding = {
  id: DEMO_CONFIG.weddingId,
  title: 'Emma & James',
  partner_one_name: 'Emma',
  partner_two_name: 'James',
  wedding_date: '2027-04-24',
  date_confirmed: true,
  timezone: 'Europe/London',
  status: 'active',
  slug: DEMO_CONFIG.publicSlug,
  location: 'Bath, Somerset',
  welcome_message: 'We are so excited to celebrate our special day with you. Thank you for being part of our journey — we cannot wait to see you in Bath!',
  dress_code: 'Formal — black tie optional. Ladies, think spring garden party elegance. Gentlemen, suits or tuxedos. The Orangery can be warm in April, so layers are your friend.',
  contact_information: 'If you have any questions, please contact us at emma.and.james@example.com or call Sophie (Maid of Honour) on 07700 900123.',
  parking_notes: 'Limited parking is available at St Mary\'s Church. For the reception, The Orangery has a private car park with 40 spaces. Additional on-street parking is available on Great Pulteney Street. We recommend taxis or the Park & Ride from Odd Down.',
  accessibility_notes: 'St Mary\'s Church has step-free access via the north entrance. The Orangery is fully wheelchair accessible with disabled lavatories on the ground floor. If you have specific accessibility requirements, please let us know on your RSVP.',
  children_policy: 'Children are welcome at the ceremony and reception. We have arranged a supervised children\'s corner with activities during the wedding breakfast. Please indicate on your RSVP if your children will be attending so we can plan accordingly.',
  plus_one_policy: 'Named plus-ones are included on your invitation. If your invitation includes a plus-one, you will see their name on your RSVP form. Please contact us if you have any questions.',
  hashtag: '#EmmaAndJames2027',
};

export const demoVenues: DemoWeddingVenue[] = [
  {
    id: 'demo-venue-stmarys',
    wedding_id: DEMO_CONFIG.weddingId,
    venue_type: 'ceremony',
    name: 'St Mary\'s Church',
    address_line_1: 'Darlington Street',
    city: 'Bath',
    county_or_region: 'Somerset',
    postcode: 'BA2 6EB',
    country: 'United Kingdom',
    is_public: true,
  },
  {
    id: 'demo-venue-orangery',
    wedding_id: DEMO_CONFIG.weddingId,
    venue_type: 'reception',
    name: 'The Orangery',
    address_line_1: 'Great Pulteney Street',
    city: 'Bath',
    county_or_region: 'Somerset',
    postcode: 'BA2 4DB',
    country: 'United Kingdom',
    is_public: true,
  },
  {
    id: 'demo-venue-marlborough',
    wedding_id: DEMO_CONFIG.weddingId,
    venue_type: 'other',
    name: 'The Marlborough Tavern',
    address_line_1: '35 Marlborough Buildings',
    city: 'Bath',
    county_or_region: 'Somerset',
    postcode: 'BA1 2LY',
    country: 'United Kingdom',
    is_public: true,
  },
];

export const demoEvents: DemoWeddingEvent[] = [
  {
    id: 'demo-event-ceremony',
    wedding_id: DEMO_CONFIG.weddingId,
    event_type: 'ceremony',
    name: 'Wedding Ceremony',
    start_at: '2027-04-24T13:00:00+01:00',
    end_at: '2027-04-24T14:00:00+01:00',
    venue_id: 'demo-venue-stmarys',
    dress_code: 'Formal',
    description: 'The wedding ceremony will take place at the beautiful St Mary\'s Church in Bathwick.',
    guest_description: 'Please arrive by 12:30 to be seated before the bride arrives. The ceremony will be followed by a short walk or drive to The Orangery for the reception.',
    is_public: true,
    sort_order: 1,
    visibility: 'public',
    status: 'published',
    reveal_at: null,
    published_at: '2026-08-15T10:00:00+01:00',
    arrival_offset_minutes: 30,
    parking_notes: 'Limited parking available at St Mary\'s Church. Additional spaces at the Bathwick Hill car park, 5 minutes walk.',
    transport_notes: 'A vintage Routemaster bus will shuttle guests from The Orangery to the church before the ceremony and back afterwards.',
    accessibility_notes: 'Step-free access via the north entrance. Please let us know if you need assistance.',
    children_notes: 'Children are welcome. A quiet corner with colouring books will be available at the back of the church.',
    venue_name: 'St Mary\'s Church',
    venue_city: 'Bath',
  },
  {
    id: 'demo-event-reception',
    wedding_id: DEMO_CONFIG.weddingId,
    event_type: 'reception',
    name: 'Wedding Breakfast & Reception',
    start_at: '2027-04-24T15:00:00+01:00',
    end_at: '2027-04-25T00:00:00+01:00',
    venue_id: 'demo-venue-orangery',
    dress_code: 'Formal — black tie optional',
    description: 'Join us at The Orangery for a champagne reception, three-course wedding breakfast, speeches, and an evening of dancing.',
    guest_description: 'Champagne reception starts at 3pm on the Orangery lawn (weather permitting). Wedding breakfast served at 5pm. The Night Owls Band takes the stage at 8pm.',
    is_public: true,
    sort_order: 2,
    visibility: 'public',
    status: 'published',
    reveal_at: null,
    published_at: '2026-08-15T10:00:00+01:00',
    arrival_offset_minutes: 0,
    parking_notes: 'The Orangery has a private car park with 40 spaces. Additional on-street parking on Great Pulteney Street. Overnight parking permitted.',
    transport_notes: 'Taxis available from outside the venue. We recommend pre-booking your return journey.',
    accessibility_notes: 'Fully wheelchair accessible with disabled lavatories on the ground floor.',
    children_notes: 'Supervised children\'s corner with activities during the wedding breakfast. A children\'s menu is available.',
    venue_name: 'The Orangery',
    venue_city: 'Bath',
  },
  {
    id: 'demo-event-welcome',
    wedding_id: DEMO_CONFIG.weddingId,
    event_type: 'welcome',
    name: 'Welcome Drinks',
    start_at: '2027-04-23T19:00:00+01:00',
    end_at: '2027-04-23T21:30:00+01:00',
    venue_id: 'demo-venue-marlborough',
    dress_code: 'Smart casual',
    description: 'For guests arriving on Friday evening, join us for welcome drinks at The Marlborough Tavern.',
    guest_description: 'Drop in any time between 7pm and 9:30pm. We\'ve reserved the back room. A chance to catch up with everyone before the big day!',
    is_public: true,
    sort_order: 0,
    visibility: 'public',
    status: 'published',
    reveal_at: null,
    published_at: '2026-09-01T10:00:00+01:00',
    arrival_offset_minutes: 0,
    parking_notes: 'Street parking available on Marlborough Buildings and surrounding streets.',
    transport_notes: '10-minute walk from Bath city centre. Bus routes 4 and 6 stop nearby.',
    accessibility_notes: 'The back room has step-free access from the garden entrance.',
    children_notes: 'Children welcome until 8:30pm.',
    venue_name: 'The Marlborough Tavern',
    venue_city: 'Bath',
  },
  {
    id: 'demo-event-farewell',
    wedding_id: DEMO_CONFIG.weddingId,
    event_type: 'day_after',
    name: 'Farewell Brunch',
    start_at: '2027-04-25T10:30:00+01:00',
    end_at: '2027-04-25T13:00:00+01:00',
    venue_id: 'demo-venue-orangery',
    dress_code: 'Casual',
    description: 'A relaxed brunch at The Orangery before everyone heads home.',
    guest_description: 'Drop in any time between 10:30am and 1pm. We\'d love to say goodbye properly before you head off. Buffet-style brunch with hot and cold options.',
    is_public: true,
    sort_order: 3,
    visibility: 'public',
    status: 'published',
    reveal_at: null,
    published_at: '2026-09-01T10:00:00+01:00',
    arrival_offset_minutes: 0,
    parking_notes: 'Same as the Orangery — private car park with 40 spaces.',
    transport_notes: '',
    accessibility_notes: 'Same as the reception — fully wheelchair accessible.',
    children_notes: 'Children welcome. High chairs available.',
    venue_name: 'The Orangery',
    venue_city: 'Bath',
  },
  {
    id: 'demo-event-evening',
    wedding_id: DEMO_CONFIG.weddingId,
    event_type: 'evening',
    name: 'Evening Celebration',
    start_at: '2027-04-24T19:00:00+01:00',
    end_at: '2027-04-25T00:00:00+01:00',
    venue_id: 'demo-venue-orangery',
    dress_code: 'Party wear',
    description: 'Evening-only guests join us for dancing, drinks, and late-night celebrations.',
    guest_description: 'Evening guests, please arrive from 7pm. The Night Owls Band plays from 8pm, followed by a DJ until midnight. Late-night snacks served at 10pm.',
    is_public: true,
    sort_order: 4,
    visibility: 'public',
    status: 'published',
    reveal_at: null,
    published_at: '2026-09-05T10:00:00+01:00',
    arrival_offset_minutes: 0,
    parking_notes: '',
    transport_notes: '',
    accessibility_notes: '',
    children_notes: '',
    venue_name: 'The Orangery',
    venue_city: 'Bath',
  },
];

export const demoEventAudiences: DemoEventAudience[] = [];