import type { DemoInvitation, DemoInvitationRecipient } from './demoTypes';
import { DEMO_CONFIG } from './demoConfig';

const W = DEMO_CONFIG.weddingId;

export const demoInvitations: DemoInvitation[] = [
  { id: 'demo-inv-bennett', wedding_id: W, household_id: 'demo-hh-bennett', invitation_type: 'household', internal_name: 'Oliver Bennett — Best Man', formal_recipient_name: 'Mr Oliver Bennett & Miss Charlotte Ellis', informal_greeting: 'Oliver & Charlotte', delivery_method: 'email', language_code: 'en-GB', rsvp_deadline: '2027-02-28', status: 'ready', template_id: '' },
  { id: 'demo-inv-carter', wedding_id: W, household_id: 'demo-hh-carter', invitation_type: 'individual', internal_name: 'Sophie Carter — Maid of Honour', formal_recipient_name: 'Miss Sophie Carter', informal_greeting: 'Sophie', delivery_method: 'email', language_code: 'en-GB', rsvp_deadline: '2027-03-24', status: 'sent', template_id: '' },
  { id: 'demo-inv-patel', wedding_id: W, household_id: 'demo-hh-patel', invitation_type: 'household', internal_name: 'Priya Patel & Family', formal_recipient_name: 'Dr Priya Patel, Mr Raj Patel & Family', informal_greeting: 'Priya, Raj & family', delivery_method: 'email', language_code: 'en-GB', rsvp_deadline: '2027-03-24', status: 'sent', template_id: '' },
  { id: 'demo-inv-bennett-sr', wedding_id: W, household_id: 'demo-hh-bennett-sr', invitation_type: 'couple', internal_name: 'Margaret & David Bennett', formal_recipient_name: 'Mrs Margaret Bennett & Mr David Bennett', informal_greeting: 'Mum & Dad', delivery_method: 'post', language_code: 'en-GB', rsvp_deadline: '2027-03-24', status: 'sent', template_id: '' },
  { id: 'demo-inv-carter-sr', wedding_id: W, household_id: 'demo-hh-carter-sr', invitation_type: 'couple', internal_name: 'Helen & Philip Carter', formal_recipient_name: 'Mrs Helen Carter & Mr Philip Carter', informal_greeting: 'Mum & Dad', delivery_method: 'email', language_code: 'en-GB', rsvp_deadline: '2027-03-24', status: 'sent', template_id: '' },
  { id: 'demo-inv-wood', wedding_id: W, household_id: 'demo-hh-wood', invitation_type: 'individual', internal_name: 'Amelia Wood — Bridesmaid', formal_recipient_name: 'Miss Amelia Wood', informal_greeting: 'Amelia', delivery_method: 'email', language_code: 'en-GB', rsvp_deadline: '2027-03-24', status: 'sent', template_id: '' },
  { id: 'demo-inv-okonkwo', wedding_id: W, household_id: 'demo-hh-okonkwo', invitation_type: 'couple', internal_name: 'Ruth Okonkwo & Tom Davies', formal_recipient_name: 'Miss Ruth Okonkwo & Mr Tom Davies', informal_greeting: 'Ruth & Tom', delivery_method: 'email', language_code: 'en-GB', rsvp_deadline: '2027-03-24', status: 'sent', template_id: '' },
  { id: 'demo-inv-whitfield', wedding_id: W, household_id: 'demo-hh-whitfield', invitation_type: 'individual', internal_name: 'George Whitfield — Groomsman', formal_recipient_name: 'Mr George Whitfield', informal_greeting: 'George', delivery_method: 'email', language_code: 'en-GB', rsvp_deadline: '2027-03-24', status: 'sent', template_id: '' },
  { id: 'demo-inv-chen', wedding_id: W, household_id: 'demo-hh-chen', invitation_type: 'individual', internal_name: 'Daniel Chen — Groomsman', formal_recipient_name: 'Mr Daniel Chen', informal_greeting: 'Daniel', delivery_method: 'email', language_code: 'en-GB', rsvp_deadline: '2027-03-24', status: 'sent', template_id: '' },
  { id: 'demo-inv-simmons', wedding_id: W, household_id: 'demo-hh-simmons', invitation_type: 'individual', internal_name: 'Laura Simmons', formal_recipient_name: 'Miss Laura Simmons', informal_greeting: 'Laura', delivery_method: 'email', language_code: 'en-GB', rsvp_deadline: '2027-03-24', status: 'sent', template_id: '' },
  { id: 'demo-inv-walker', wedding_id: W, household_id: 'demo-hh-walker', invitation_type: 'individual', internal_name: 'James Walker', formal_recipient_name: 'Mr James Walker', informal_greeting: 'James', delivery_method: 'email', language_code: 'en-GB', rsvp_deadline: '2027-03-24', status: 'sent', template_id: '' },
  { id: 'demo-inv-hussain', wedding_id: W, household_id: 'demo-hh-hussain', invitation_type: 'couple', internal_name: 'Nadia Hussain & Ahmed Khalil', formal_recipient_name: 'Dr Nadia Hussain & Mr Ahmed Khalil', informal_greeting: 'Nadia & Ahmed', delivery_method: 'email', language_code: 'en-GB', rsvp_deadline: '2027-03-24', status: 'sent', template_id: '' },
  { id: 'demo-inv-carol', wedding_id: W, household_id: 'demo-hh-carol', invitation_type: 'individual', internal_name: 'Carol Bennett — Aunt', formal_recipient_name: 'Mrs Carol Bennett', informal_greeting: 'Aunt Carol', delivery_method: 'post', language_code: 'en-GB', rsvp_deadline: '2027-03-24', status: 'sent', template_id: '' },
  { id: 'demo-inv-thorne', wedding_id: W, household_id: 'demo-hh-thorne', invitation_type: 'individual', internal_name: 'Henry Thorne', formal_recipient_name: 'Mr Henry Thorne', informal_greeting: 'Henry', delivery_method: 'email', language_code: 'en-GB', rsvp_deadline: '2027-03-24', status: 'sent', template_id: '' },
  { id: 'demo-inv-frost', wedding_id: W, household_id: 'demo-hh-frost', invitation_type: 'couple', internal_name: 'Eleanor & Robert Frost', formal_recipient_name: 'Mrs Eleanor Frost & Mr Robert Frost', informal_greeting: 'Eleanor & Robert', delivery_method: 'email', language_code: 'en-GB', rsvp_deadline: '2027-03-24', status: 'sent', template_id: '' },
  { id: 'demo-inv-maya', wedding_id: W, household_id: 'demo-hh-maya', invitation_type: 'individual', internal_name: 'Maya Okonkwo — Evening', formal_recipient_name: 'Miss Maya Okonkwo', informal_greeting: 'Maya', delivery_method: 'email', language_code: 'en-GB', rsvp_deadline: '2027-02-28', status: 'draft', template_id: '' },
];

export const demoInvitationRecipients: DemoInvitationRecipient[] = [
  { id: 'demo-recip-bennett', wedding_id: W, invitation_id: 'demo-inv-bennett', guest_id: 'demo-guest-oliver', recipient_role: 'primary', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: true },
  { id: 'demo-recip-carter', wedding_id: W, invitation_id: 'demo-inv-carter', guest_id: 'demo-guest-sophie', recipient_role: 'primary', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: false },
  { id: 'demo-recip-patriya', wedding_id: W, invitation_id: 'demo-inv-patel', guest_id: 'demo-guest-priya', recipient_role: 'primary', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: false },
  { id: 'demo-recip-patraj', wedding_id: W, invitation_id: 'demo-inv-patel', guest_id: 'demo-guest-raj', recipient_role: 'partner', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: false },
  { id: 'demo-recip-patanika', wedding_id: W, invitation_id: 'demo-inv-patel', guest_id: 'demo-guest-anika', recipient_role: 'child', ceremony_included: true, reception_included: true, evening_included: false, plus_one_allowed: false },
  { id: 'demo-recip-patrohan', wedding_id: W, invitation_id: 'demo-inv-patel', guest_id: 'demo-guest-rohan', recipient_role: 'child', ceremony_included: true, reception_included: true, evening_included: false, plus_one_allowed: false },
  { id: 'demo-recip-margaret', wedding_id: W, invitation_id: 'demo-inv-bennett-sr', guest_id: 'demo-guest-margaret', recipient_role: 'primary', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: false },
  { id: 'demo-recip-david', wedding_id: W, invitation_id: 'demo-inv-bennett-sr', guest_id: 'demo-guest-david', recipient_role: 'partner', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: false },
  { id: 'demo-recip-helen', wedding_id: W, invitation_id: 'demo-inv-carter-sr', guest_id: 'demo-guest-helen', recipient_role: 'primary', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: false },
  { id: 'demo-recip-philip', wedding_id: W, invitation_id: 'demo-inv-carter-sr', guest_id: 'demo-guest-philip', recipient_role: 'partner', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: false },
  { id: 'demo-recip-amelia', wedding_id: W, invitation_id: 'demo-inv-wood', guest_id: 'demo-guest-amelia', recipient_role: 'primary', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: true },
  { id: 'demo-recip-ruth', wedding_id: W, invitation_id: 'demo-inv-okonkwo', guest_id: 'demo-guest-ruth', recipient_role: 'primary', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: false },
  { id: 'demo-recip-tom', wedding_id: W, invitation_id: 'demo-inv-okonkwo', guest_id: 'demo-guest-tom', recipient_role: 'partner', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: false },
  { id: 'demo-recip-george', wedding_id: W, invitation_id: 'demo-inv-whitfield', guest_id: 'demo-guest-george', recipient_role: 'primary', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: true },
  { id: 'demo-recip-daniel', wedding_id: W, invitation_id: 'demo-inv-chen', guest_id: 'demo-guest-daniel', recipient_role: 'primary', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: false },
  { id: 'demo-recip-laura', wedding_id: W, invitation_id: 'demo-inv-simmons', guest_id: 'demo-guest-laura', recipient_role: 'primary', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: true },
  { id: 'demo-recip-jamesw', wedding_id: W, invitation_id: 'demo-inv-walker', guest_id: 'demo-guest-james-w', recipient_role: 'primary', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: true },
  { id: 'demo-recip-nadia', wedding_id: W, invitation_id: 'demo-inv-hussain', guest_id: 'demo-guest-nadia', recipient_role: 'primary', ceremony_included: false, reception_included: true, evening_included: true, plus_one_allowed: false },
  { id: 'demo-recip-ahmed', wedding_id: W, invitation_id: 'demo-inv-hussain', guest_id: 'demo-guest-ahmed', recipient_role: 'partner', ceremony_included: false, reception_included: true, evening_included: true, plus_one_allowed: false },
  { id: 'demo-recip-carol', wedding_id: W, invitation_id: 'demo-inv-carol', guest_id: 'demo-guest-aunt-carol', recipient_role: 'primary', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: false },
  { id: 'demo-recip-henry', wedding_id: W, invitation_id: 'demo-inv-thorne', guest_id: 'demo-guest-henry', recipient_role: 'primary', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: true },
  { id: 'demo-recip-eleanor', wedding_id: W, invitation_id: 'demo-inv-frost', guest_id: 'demo-guest-eleanor', recipient_role: 'primary', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: false },
  { id: 'demo-recip-robert', wedding_id: W, invitation_id: 'demo-inv-frost', guest_id: 'demo-guest-robert', recipient_role: 'partner', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: false },
  { id: 'demo-recip-maya', wedding_id: W, invitation_id: 'demo-inv-maya', guest_id: 'demo-guest-maya', recipient_role: 'primary', ceremony_included: false, reception_included: false, evening_included: true, plus_one_allowed: false },
];