import type { DemoTravelPlace } from './demoTypes';
import { DEMO_CONFIG } from './demoConfig';

const W = DEMO_CONFIG.weddingId;

export const demoTravelPlaces: DemoTravelPlace[] = [
  {
    id: 'demo-place-marlborough', wedding_id: W, name: 'The Marlborough Tavern', category: 'Restaurant',
    short_description: 'Cosy gastropub a short walk from The Orangery. Excellent Sunday roasts and local ales.',
    address: '35 Marlborough Buildings', city: 'Bath', postcode: 'BA1 2LY',
    distance_miles: 0.3, journey_time_minutes: 5,
    website_url: 'https://www.marlborough-tavern.com', phone: '01225 423307',
    approval_status: 'approved', featured: true,
    couple_note: 'We will be here for welcome drinks on Friday evening — come say hello!', price_tag: 'standard',
  },
  {
    id: 'demo-place-royal-crescent', wedding_id: W, name: 'The Royal Crescent Hotel & Spa', category: 'Hotel',
    short_description: 'Five-star luxury hotel in Bath\'s iconic Royal Crescent. Beautiful spa and gardens.',
    address: '16 Royal Crescent', city: 'Bath', postcode: 'BA1 2LS',
    distance_miles: 0.6, journey_time_minutes: 12,
    website_url: 'https://www.royalcrescent.co.uk', phone: '01225 823333',
    approval_status: 'approved', featured: true,
    couple_note: 'We have a small room block here — mention the Bennett-Carter wedding when booking.', price_tag: 'luxury',
  },
  {
    id: 'demo-place-bath-spa-station', wedding_id: W, name: 'Bath Spa Railway Station', category: 'Railway station',
    short_description: 'Main railway station with direct trains to London Paddington (90 min) and Bristol (15 min).',
    address: 'Dorchester Street', city: 'Bath', postcode: 'BA1 1SU',
    distance_miles: 0.8, journey_time_minutes: 15,
    website_url: 'https://www.gwr.com', phone: '',
    approval_status: 'approved', featured: false,
    couple_note: 'Taxis are available outside the station. The Orangery is a 15-minute walk or 5-minute taxi ride.', price_tag: 'budget',
  },
  {
    id: 'demo-place-thermae-spa', wedding_id: W, name: 'Thermae Bath Spa', category: 'Local attraction',
    short_description: 'Britain\'s only natural thermal spa. Rooftop pool with stunning views over Bath.',
    address: 'Hetling Pump Room, Hot Bath Street', city: 'Bath', postcode: 'BA1 1SJ',
    distance_miles: 0.5, journey_time_minutes: 10,
    website_url: 'https://www.thermaebathspa.com', phone: '01225 331234',
    approval_status: 'approved', featured: true,
    couple_note: 'Treat yourself the morning after! Book spa sessions in advance — they fill up quickly.', price_tag: 'luxury',
  },
  {
    id: 'demo-place-pump-room', wedding_id: W, name: 'The Pump Room', category: 'Café',
    short_description: 'Elegant Georgian dining room next to the Roman Baths. Famous for afternoon tea.',
    address: 'Stall Street', city: 'Bath', postcode: 'BA1 1LZ',
    distance_miles: 0.4, journey_time_minutes: 8,
    website_url: 'https://www.romanbaths.co.uk', phone: '01225 444477',
    approval_status: 'approved', featured: false,
    couple_note: 'Perfect spot for a pre-wedding afternoon tea. Book ahead for weekends.', price_tag: 'standard',
  },
  {
    id: 'demo-place-abbey-taxi', wedding_id: W, name: 'Abbey Taxis Bath', category: 'Taxi',
    short_description: 'Reliable local taxi firm. Pre-book for wedding day transport.',
    address: '3 Charles Street', city: 'Bath', postcode: 'BA1 1HU',
    distance_miles: 0, journey_time_minutes: 0,
    website_url: 'https://www.abbeytaxisbath.co.uk', phone: '01225 444444',
    approval_status: 'approved', featured: false,
    couple_note: 'Recommended for getting between venues. Mention you are with the wedding party.', price_tag: 'standard',
  },
  {
    id: 'demo-place-charlotte-st-carpark', wedding_id: W, name: 'Charlotte Street Car Park', category: 'Parking',
    short_description: 'Long-stay car park close to the city centre. Overnight parking available.',
    address: 'Charlotte Street', city: 'Bath', postcode: 'BA1 2NE',
    distance_miles: 0.7, journey_time_minutes: 14,
    website_url: 'https://www.bathnes.gov.uk', phone: '',
    approval_status: 'approved', featured: false,
    couple_note: 'Best option for overnight parking. £15 per 24 hours.', price_tag: 'budget',
  },
  {
    id: 'demo-place-boots-pharmacy', wedding_id: W, name: 'Boots Pharmacy', category: 'Pharmacy',
    short_description: 'Central pharmacy for essentials, toiletries, and medicines.',
    address: 'Westgate Street', city: 'Bath', postcode: 'BA1 1EQ',
    distance_miles: 0.5, journey_time_minutes: 10,
    website_url: 'https://www.boots.com', phone: '01225 464411',
    approval_status: 'approved', featured: false,
    couple_note: 'Open until 5:30pm on Saturday. Stock up on plasters for dancing feet!', price_tag: 'budget',
  },
  {
    id: 'demo-place-waitrose', wedding_id: W, name: 'Waitrose & Partners', category: 'Supermarket',
    short_description: 'Supermarket with café, fresh food, and a good wine selection.',
    address: 'The Podium, Northgate Street', city: 'Bath', postcode: 'BA1 5AL',
    distance_miles: 0.6, journey_time_minutes: 12,
    website_url: 'https://www.waitrose.com', phone: '01225 462011',
    approval_status: 'approved', featured: false,
    couple_note: 'Handy for picking up anything you need for your stay. Good breakfast options too.', price_tag: 'standard',
  },
  {
    id: 'demo-place-yo-bath', wedding_id: W, name: 'The Bird, Bath', category: 'Hotel',
    short_description: 'Boutique hotel with quirky décor, garden, and excellent brunch menu. 5 minutes from The Orangery.',
    address: '18-19 Pulteney Road', city: 'Bath', postcode: 'BA2 4EZ',
    distance_miles: 0.5, journey_time_minutes: 10,
    website_url: 'https://www.thebirdbath.co.uk', phone: '01225 460606',
    approval_status: 'pending', featured: false,
    couple_note: 'Currently checking availability for a small room block — will update soon.', price_tag: 'standard',
  },
];