import type { DemoGalleryItem, DemoGalleryAlbum, DemoGallerySettings } from './demoTypes';
import { DEMO_CONFIG } from './demoConfig';

const W = DEMO_CONFIG.weddingId;

export const demoGalleryAlbums: DemoGalleryAlbum[] = [
  { id: 'demo-album-engagement', wedding_id: W, name: 'Engagement Shoot', description: 'Our engagement photos at Prior Park Landscape Garden — October 2026', cover_image_index: 0 },
  { id: 'demo-album-welcome', wedding_id: W, name: 'Welcome Drinks', description: 'Friday evening at The Marlborough Tavern', cover_image_index: 0 },
  { id: 'demo-album-ceremony', wedding_id: W, name: 'Ceremony', description: 'The ceremony at St Mary\'s Church', cover_image_index: 0 },
  { id: 'demo-album-reception', wedding_id: W, name: 'Reception & Evening', description: 'Celebrations at The Orangery', cover_image_index: 0 },
];

export const demoGalleryItems: DemoGalleryItem[] = [
  // Approved photos (12) - all on wall
  { id: 'demo-gallery-1', wedding_id: W, album_id: 'demo-album-engagement', image_src: 'https://readdy.ai/api/search-image?query=Couple%20walking%20hand%20in%20hand%20through%20a%20historic%20palladian%20bridge%20in%20autumn%2C%20golden%20leaves%2C%20soft%20romantic%20lighting%2C%20editorial%20wedding%20photography%20style%2C%20warm%20earthy%20tones&width=800&height=600&seq=wedora-demo-gallery-1&orientation=landscape', caption: 'Walking through the Palladian Bridge at Prior Park', uploader_name: 'Bath Wedding Photography', upload_time: '2027-01-15T10:30:00+00:00', moderation_status: 'approved', favourite_count: 3, reported: false, ai_label: 'Couple outdoors, autumn scene', wall_visible: true },
  { id: 'demo-gallery-2', wedding_id: W, album_id: 'demo-album-engagement', image_src: 'https://readdy.ai/api/search-image?query=Engaged%20couple%20laughing%20together%20on%20a%20stone%20bench%20in%20a%20romantic%20English%20garden%2C%20soft%20bokeh%20background%2C%20editorial%20photography%2C%20warm%20natural%20light&width=800&height=600&seq=wedora-demo-gallery-2&orientation=landscape', caption: 'A quiet moment in the garden', uploader_name: 'Bath Wedding Photography', upload_time: '2027-01-15T10:32:00+00:00', moderation_status: 'approved', favourite_count: 2, reported: false, ai_label: 'Couple portrait, garden setting', wall_visible: true },
  { id: 'demo-gallery-3', wedding_id: W, album_id: 'demo-album-engagement', image_src: 'https://readdy.ai/api/search-image?query=Close%20up%20detail%20shot%20of%20engagement%20ring%20resting%20on%20autumn%20leaves%2C%20shallow%20depth%20of%20field%2C%20warm%20golden%20tone%2C%20fine%20art%20wedding%20photography&width=800&height=600&seq=wedora-demo-gallery-3&orientation=landscape', caption: 'The ring, surrounded by autumn leaves', uploader_name: 'Bath Wedding Photography', upload_time: '2027-01-15T10:35:00+00:00', moderation_status: 'approved', favourite_count: 5, reported: false, ai_label: 'Ring detail, macro photography', wall_visible: true },
  { id: 'demo-gallery-4', wedding_id: W, album_id: 'demo-album-welcome', image_src: 'https://readdy.ai/api/search-image?query=Warm%20cozy%20pub%20interior%20with%20friends%20raising%20glasses%20of%20champagne%2C%20fairy%20lights%2C%20candid%20moment%2C%20documentary%20wedding%20photography%20style%2C%20natural%20warm%20lighting&width=800&height=600&seq=wedora-demo-gallery-4&orientation=landscape', caption: 'Welcome drinks at The Marlborough Tavern', uploader_name: 'Sophie Carter', upload_time: '2027-01-20T08:00:00+00:00', moderation_status: 'approved', favourite_count: 1, reported: false, ai_label: 'Group gathering, indoor pub', wall_visible: true },
  { id: 'demo-gallery-5', wedding_id: W, album_id: 'demo-album-welcome', image_src: 'https://readdy.ai/api/search-image?query=Bride%20and%20groom%20arriving%20at%20a%20quaint%20English%20pub%20at%20dusk%2C%20warm%20golden%20light%20spilling%20from%20windows%2C%20romantic%20editorial%20style&width=800&height=600&seq=wedora-demo-gallery-5&orientation=landscape', caption: 'Emma & James arrive at the welcome drinks', uploader_name: 'Amelia Wood', upload_time: '2027-01-20T08:05:00+00:00', moderation_status: 'approved', favourite_count: 4, reported: false, ai_label: 'Couple arriving, evening scene', wall_visible: true },
  { id: 'demo-gallery-6', wedding_id: W, album_id: 'demo-album-ceremony', image_src: 'https://readdy.ai/api/search-image?query=Beautiful%20stone%20church%20interior%20with%20floral%20arrangements%20along%20the%20aisle%2C%20soft%20candlelight%2C%20empty%20pews%20waiting%20for%20guests%2C%20editorial%20wedding%20detail%20shot&width=800&height=600&seq=wedora-demo-gallery-6&orientation=landscape', caption: 'St Mary\'s Church, ready for the ceremony', uploader_name: 'Bath Wedding Photography', upload_time: '2027-01-22T09:00:00+00:00', moderation_status: 'approved', favourite_count: 0, reported: false, ai_label: 'Church interior, floral decor', wall_visible: true },
  { id: 'demo-gallery-7', wedding_id: W, album_id: 'demo-album-ceremony', image_src: 'https://readdy.ai/api/search-image?query=Bride%20walking%20down%20church%20aisle%20with%20her%20father%2C%20sunlight%20streaming%20through%20stained%20glass%20windows%2C%20emotional%20moment%2C%20fine%20art%20wedding%20photography&width=800&height=600&seq=wedora-demo-gallery-7&orientation=landscape', caption: 'Emma walks down the aisle with her father', uploader_name: 'Bath Wedding Photography', upload_time: '2027-01-22T09:05:00+00:00', moderation_status: 'approved', favourite_count: 7, reported: false, ai_label: 'Bride walking aisle, church ceremony', wall_visible: true },
  { id: 'demo-gallery-8', wedding_id: W, album_id: 'demo-album-ceremony', image_src: 'https://readdy.ai/api/search-image?query=Couple%20exchanging%20vows%20at%20the%20altar%2C%20profile%20view%2C%20candlelit%20church%2C%20emotional%20documentary%20wedding%20photography%2C%20warm%20ambient%20light&width=800&height=600&seq=wedora-demo-gallery-8&orientation=landscape', caption: 'Exchanging vows at the altar', uploader_name: 'Bath Wedding Photography', upload_time: '2027-01-22T09:10:00+00:00', moderation_status: 'approved', favourite_count: 8, reported: false, ai_label: 'Couple at altar, ceremony', wall_visible: true },
  { id: 'demo-gallery-9', wedding_id: W, album_id: 'demo-album-reception', image_src: 'https://readdy.ai/api/search-image?query=Elegant%20wedding%20reception%20in%20a%20glass%20orangery%20filled%20with%20flowers%20and%20candlelight%2C%20round%20tables%20with%20white%20linen%2C%20romantic%20atmosphere%2C%20editorial%20photography&width=800&height=600&seq=wedora-demo-gallery-9&orientation=landscape', caption: 'The Orangery, dressed for the reception', uploader_name: 'Bath Wedding Photography', upload_time: '2027-01-25T11:00:00+00:00', moderation_status: 'approved', favourite_count: 2, reported: false, ai_label: 'Reception venue, tablescape', wall_visible: true },
  { id: 'demo-gallery-10', wedding_id: W, album_id: 'demo-album-reception', image_src: 'https://readdy.ai/api/search-image?query=Wedding%20couple%20sharing%20their%20first%20dance%20under%20twinkling%20fairy%20lights%2C%20surrounded%20by%20guests%2C%20romantic%20blurred%20background%2C%20fine%20art%20photography&width=800&height=600&seq=wedora-demo-gallery-10&orientation=landscape', caption: 'First dance — a moment to remember', uploader_name: 'Bath Wedding Photography', upload_time: '2027-01-25T11:05:00+00:00', moderation_status: 'approved', favourite_count: 6, reported: false, ai_label: 'First dance, evening reception', wall_visible: true },
  { id: 'demo-gallery-11', wedding_id: W, album_id: 'demo-album-reception', image_src: 'https://readdy.ai/api/search-image?query=Candid%20photo%20of%20wedding%20guests%20laughing%20and%20dancing%20at%20a%20reception%2C%20joyful%20atmosphere%2C%20warm%20lighting%2C%20documentary%20wedding%20photography%20style&width=800&height=600&seq=wedora-demo-gallery-11&orientation=landscape', caption: 'Everyone on the dance floor!', uploader_name: 'Ruth Okonkwo', upload_time: '2027-01-26T14:00:00+00:00', moderation_status: 'approved', favourite_count: 3, reported: false, ai_label: 'Guests dancing, celebration', wall_visible: true },
  { id: 'demo-gallery-12', wedding_id: W, album_id: 'demo-album-reception', image_src: 'https://readdy.ai/api/search-image?query=Three%20tier%20elegant%20wedding%20cake%20with%20fresh%20flowers%20on%20a%20decorated%20cake%20table%2C%20golden%20cutlery%2C%20soft%20bokeh%20background%2C%20editorial%20detail%20shot&width=800&height=600&seq=wedora-demo-gallery-12&orientation=landscape', caption: 'The wedding cake — almost too beautiful to cut!', uploader_name: 'Amelia Wood', upload_time: '2027-01-26T14:10:00+00:00', moderation_status: 'approved', favourite_count: 4, reported: false, ai_label: 'Wedding cake detail', wall_visible: true },
  // Pending review (4) - not on wall
  { id: 'demo-gallery-13', wedding_id: W, album_id: 'demo-album-reception', image_src: 'https://readdy.ai/api/search-image?query=Candid%20photo%20of%20guests%20at%20a%20wedding%20bar%2C%20laughter%20and%20drinks%2C%20warm%20lighting%2C%20documentary%20style%20shot&width=800&height=600&seq=wedora-demo-gallery-13&orientation=landscape', caption: 'Drinks at the bar!', uploader_name: 'George Whitfield', upload_time: '2027-01-27T09:00:00+00:00', moderation_status: 'needs_review', favourite_count: 0, reported: false, ai_label: 'Guests at bar, social setting', wall_visible: false },
  { id: 'demo-gallery-14', wedding_id: W, album_id: 'demo-album-reception', image_src: 'https://readdy.ai/api/search-image?query=Wedding%20bouquet%20toss%20moment%2C%20group%20of%20women%20reaching%20up%2C%20joyful%20expressions%2C%20motion%20blur%20effect%2C%20energetic%20wedding%20photography&width=800&height=600&seq=wedora-demo-gallery-14&orientation=landscape', caption: 'The bouquet toss — who caught it?!', uploader_name: 'Tom Davies', upload_time: '2027-01-27T09:15:00+00:00', moderation_status: 'needs_review', favourite_count: 0, reported: false, ai_label: 'Bouquet toss, action shot', wall_visible: false },
  { id: 'demo-gallery-15', wedding_id: W, album_id: 'demo-album-ceremony', image_src: 'https://readdy.ai/api/search-image?query=Wedding%20guests%20throwing%20confetti%20outside%20a%20stone%20church%2C%20newlywed%20couple%20in%20the%20middle%2C%20bright%20sunny%20day%2C%20celebratory%20moment&width=800&height=600&seq=wedora-demo-gallery-15&orientation=landscape', caption: 'Confetti! Best moment ever', uploader_name: 'Priya Patel', upload_time: '2027-01-28T10:00:00+00:00', moderation_status: 'needs_review', favourite_count: 0, reported: false, ai_label: 'Confetti, church exit', wall_visible: false },
  { id: 'demo-gallery-16', wedding_id: W, album_id: 'demo-album-welcome', image_src: 'https://readdy.ai/api/search-image?query=Selfie%20style%20group%20photo%20of%20friends%20at%20a%20pub%2C%20arms%20around%20each%20other%2C%20smiling%2C%20warm%20lighting%2C%20casual%20party%20atmosphere&width=800&height=600&seq=wedora-demo-gallery-16&orientation=landscape', caption: 'Group selfie at welcome drinks!', uploader_name: 'Laura Simmons', upload_time: '2027-01-28T10:30:00+00:00', moderation_status: 'needs_review', favourite_count: 0, reported: false, ai_label: 'Group selfie, social gathering', wall_visible: false },
];

export const demoGallerySettings: DemoGallerySettings = {
  guest_uploads_enabled: true,
  couple_approval_required: true,
  auto_add_to_wall: false,
  show_uploader_names: true,
  allow_guest_downloads: true,
  allow_favourites: true,
  show_captions: true,
  wall_transition_speed: 'medium',
  wall_paused: false,
};