import type { DemoHousehold } from './demoTypes';
import { DEMO_CONFIG } from './demoConfig';

const W = DEMO_CONFIG.weddingId;

export const demoHouseholds: DemoHousehold[] = [
  { id: 'demo-hh-bennett', wedding_id: W, display_name: 'Oliver Bennett & Charlotte Ellis', formal_invitation_name: 'Mr Oliver Bennett & Miss Charlotte Ellis', informal_greeting: 'Oliver & Charlotte', primary_guest_id: 'demo-guest-oliver', shared_email: 'oliver.bennett@example.com', shared_phone: '07700 900001', invitation_delivery_method: 'email', status: 'active' },
  { id: 'demo-hh-carter', wedding_id: W, display_name: 'Sophie Carter', formal_invitation_name: 'Miss Sophie Carter', informal_greeting: 'Sophie', primary_guest_id: 'demo-guest-sophie', shared_email: 'sophie.carter@example.com', shared_phone: '07700 900002', invitation_delivery_method: 'email', status: 'active' },
  { id: 'demo-hh-patel', wedding_id: W, display_name: 'The Patel Family', formal_invitation_name: 'Dr Priya Patel, Mr Raj Patel & Family', informal_greeting: 'Priya, Raj, Anika & Rohan', primary_guest_id: 'demo-guest-priya', shared_email: 'priya.patel@example.com', shared_phone: '07700 900003', invitation_delivery_method: 'email', status: 'active' },
  { id: 'demo-hh-bennett-sr', wedding_id: W, display_name: 'Margaret & David Bennett', formal_invitation_name: 'Mrs Margaret Bennett & Mr David Bennett', informal_greeting: 'Margaret & David', primary_guest_id: 'demo-guest-margaret', shared_email: 'margaret.bennett@example.com', shared_phone: '07700 900005', invitation_delivery_method: 'post', status: 'active' },
  { id: 'demo-hh-carter-sr', wedding_id: W, display_name: 'Helen & Philip Carter', formal_invitation_name: 'Mrs Helen Carter & Mr Philip Carter', informal_greeting: 'Helen & Philip', primary_guest_id: 'demo-guest-helen', shared_email: 'helen.carter@example.com', shared_phone: '07700 900007', invitation_delivery_method: 'email', status: 'active' },
  { id: 'demo-hh-wood', wedding_id: W, display_name: 'Amelia Wood', formal_invitation_name: 'Miss Amelia Wood', informal_greeting: 'Amelia', primary_guest_id: 'demo-guest-amelia', shared_email: 'amelia.wood@example.com', shared_phone: '07700 900009', invitation_delivery_method: 'email', status: 'active' },
  { id: 'demo-hh-okonkwo', wedding_id: W, display_name: 'Ruth Okonkwo & Tom Davies', formal_invitation_name: 'Miss Ruth Okonkwo & Mr Tom Davies', informal_greeting: 'Ruth & Tom', primary_guest_id: 'demo-guest-ruth', shared_email: 'ruth.okonkwo@example.com', shared_phone: '07700 900010', invitation_delivery_method: 'email', status: 'active' },
  { id: 'demo-hh-whitfield', wedding_id: W, display_name: 'George Whitfield', formal_invitation_name: 'Mr George Whitfield', informal_greeting: 'George', primary_guest_id: 'demo-guest-george', shared_email: 'george.whitfield@example.com', shared_phone: '07700 900012', invitation_delivery_method: 'email', status: 'active' },
  { id: 'demo-hh-chen', wedding_id: W, display_name: 'Daniel Chen', formal_invitation_name: 'Mr Daniel Chen', informal_greeting: 'Daniel', primary_guest_id: 'demo-guest-daniel', shared_email: 'daniel.chen@example.com', shared_phone: '07700 900013', invitation_delivery_method: 'email', status: 'active' },
  { id: 'demo-hh-simmons', wedding_id: W, display_name: 'Laura Simmons', formal_invitation_name: 'Miss Laura Simmons', informal_greeting: 'Laura', primary_guest_id: 'demo-guest-laura', shared_email: 'laura.simmons@example.com', shared_phone: '07700 900014', invitation_delivery_method: 'email', status: 'active' },
  { id: 'demo-hh-walker', wedding_id: W, display_name: 'James Walker', formal_invitation_name: 'Mr James Walker', informal_greeting: 'James', primary_guest_id: 'demo-guest-james-w', shared_email: 'james.walker@example.com', shared_phone: '07700 900015', invitation_delivery_method: 'email', status: 'active' },
  { id: 'demo-hh-hussain', wedding_id: W, display_name: 'Nadia Hussain & Ahmed Khalil', formal_invitation_name: 'Dr Nadia Hussain & Mr Ahmed Khalil', informal_greeting: 'Nadia & Ahmed', primary_guest_id: 'demo-guest-nadia', shared_email: 'nadia.hussain@example.com', shared_phone: '07700 900016', invitation_delivery_method: 'email', status: 'active' },
  { id: 'demo-hh-carol', wedding_id: W, display_name: 'Carol Bennett', formal_invitation_name: 'Mrs Carol Bennett', informal_greeting: 'Aunt Carol', primary_guest_id: 'demo-guest-aunt-carol', shared_email: 'carol.bennett@example.com', shared_phone: '07700 900018', invitation_delivery_method: 'post', status: 'active' },
  { id: 'demo-hh-thorne', wedding_id: W, display_name: 'Henry Thorne', formal_invitation_name: 'Mr Henry Thorne', informal_greeting: 'Henry', primary_guest_id: 'demo-guest-henry', shared_email: 'henry.thorne@example.com', shared_phone: '07700 900019', invitation_delivery_method: 'email', status: 'active' },
  { id: 'demo-hh-frost', wedding_id: W, display_name: 'Eleanor & Robert Frost', formal_invitation_name: 'Mrs Eleanor Frost & Mr Robert Frost', informal_greeting: 'Eleanor & Robert', primary_guest_id: 'demo-guest-eleanor', shared_email: 'eleanor.frost@example.com', shared_phone: '07700 900020', invitation_delivery_method: 'email', status: 'active' },
  { id: 'demo-hh-maya', wedding_id: W, display_name: 'Maya Okonkwo', formal_invitation_name: 'Miss Maya Okonkwo', informal_greeting: 'Maya', primary_guest_id: 'demo-guest-maya', shared_email: 'maya.okonkwo@example.com', shared_phone: '07700 900022', invitation_delivery_method: 'email', status: 'active' },
];