import type { AppNotification } from '@/types/notifications';
import { DEMO_CONFIG } from './demoConfig';

const W = DEMO_CONFIG.weddingId;
const WNAME = 'Emma & James';

export const demoNotifications: AppNotification[] = [
  {
    id: 'demo-notif-1',
    weddingId: W,
    type: 'rsvp_submitted',
    category: 'rsvp',
    priority: 'info',
    title: 'Oliver Bennett accepted',
    message: 'Oliver Bennett has accepted the invitation and will be attending.',
    route: '/app/guests',
    routeLabel: 'View guest',
    relatedType: 'guest',
    relatedId: 'demo-guest-oliver',
    dedupKey: 'rsvp-submit-oliver',
    readAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    expiresAt: null,
    actorName: 'Oliver Bennett',
    weddingName: WNAME,
  },
  {
    id: 'demo-notif-2',
    weddingId: W,
    type: 'dietary_requirement',
    category: 'guests',
    priority: 'info',
    title: 'Dietary requirement added',
    message: 'Sophie Carter has added a nut allergy requirement.',
    route: '/app/guests',
    routeLabel: 'View guest',
    relatedType: 'guest',
    relatedId: 'demo-guest-sophie',
    dedupKey: 'dietary-sophie-nut',
    readAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    expiresAt: null,
    actorName: 'Sophie Carter',
    weddingName: WNAME,
  },
  {
    id: 'demo-notif-3',
    weddingId: W,
    type: 'guest_question_new',
    category: 'questions',
    priority: 'action',
    title: 'New guest question from Maya Chen',
    message: '"What time should we arrive at the ceremony venue?" — awaiting your reply.',
    route: '/app/questions',
    routeLabel: 'Answer question',
    relatedType: 'guest_question',
    relatedId: 'demo-question-1',
    dedupKey: 'question-maya-arrival',
    readAt: null,
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    expiresAt: null,
    actorName: 'Maya Chen',
    weddingName: WNAME,
  },
  {
    id: 'demo-notif-4',
    weddingId: W,
    type: 'gallery_upload_pending',
    category: 'gallery',
    priority: 'action',
    title: '4 photos awaiting review',
    message: '4 new photos have been uploaded by guests and need moderation.',
    route: '/app/gallery?tab=moderation',
    routeLabel: 'Review photos',
    relatedType: 'gallery',
    relatedId: 'demo-gallery-batch-1',
    dedupKey: 'gallery-pending-4',
    readAt: null,
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    expiresAt: null,
    actorName: 'Multiple guests',
    weddingName: WNAME,
  },
  {
    id: 'demo-notif-5',
    weddingId: W,
    type: 'payment_overdue',
    category: 'budget',
    priority: 'urgent',
    title: 'Payment overdue — Bridal gown (£800)',
    message: 'The final balance payment for the bridal gown was due 3 days ago.',
    route: '/app/budget/payments',
    routeLabel: 'View payments',
    relatedType: 'payment',
    relatedId: 'demo-payment-overdue',
    dedupKey: 'payment-overdue-gown',
    readAt: null,
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    expiresAt: null,
    actorName: 'System',
    weddingName: WNAME,
  },
  {
    id: 'demo-notif-6',
    weddingId: W,
    type: 'task_due',
    category: 'tasks',
    priority: 'action',
    title: 'Task due: Confirm final menu with caterer',
    message: 'Assigned to Emma — due in 3 days.',
    route: '/app/tasks',
    routeLabel: 'View task',
    relatedType: 'task',
    relatedId: 'demo-task-menu',
    dedupKey: 'task-due-menu',
    readAt: null,
    createdAt: new Date(Date.now() - 3600000 * 8).toISOString(),
    expiresAt: null,
    actorName: 'System',
    weddingName: WNAME,
  },
  {
    id: 'demo-notif-7',
    weddingId: W,
    type: 'rsvp_declined',
    category: 'rsvp',
    priority: 'info',
    title: 'David Thompson declined',
    message: 'David Thompson has declined the invitation due to a prior commitment.',
    route: '/app/guests',
    routeLabel: 'View guest',
    relatedType: 'guest',
    relatedId: 'demo-guest-david',
    dedupKey: 'rsvp-decline-david',
    readAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    expiresAt: null,
    actorName: 'David Thompson',
    weddingName: WNAME,
  },
  {
    id: 'demo-notif-8',
    weddingId: W,
    type: 'supplier_appointment',
    category: 'suppliers',
    priority: 'info',
    title: 'Florist appointment confirmed',
    message: 'Tasting session with Petal & Stem — Thursday 10AM.',
    route: '/app/suppliers',
    routeLabel: 'View supplier',
    relatedType: 'supplier',
    relatedId: 'demo-supplier-florist',
    dedupKey: 'supplier-florist-appt',
    readAt: null,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    expiresAt: null,
    actorName: 'Petal & Stem',
    weddingName: WNAME,
  },
  {
    id: 'demo-notif-9',
    weddingId: W,
    type: 'rsvp_deadline',
    category: 'rsvp',
    priority: 'action',
    title: 'RSVP deadline approaching',
    message: '8 guests have not yet responded. Deadline: 28 February.',
    route: '/app/invitations/responses',
    routeLabel: 'View responses',
    relatedType: 'rsvp',
    relatedId: 'demo-rsvp-deadline',
    dedupKey: 'rsvp-deadline-8',
    readAt: null,
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    expiresAt: null,
    actorName: 'System',
    weddingName: WNAME,
  },
  {
    id: 'demo-notif-10',
    weddingId: W,
    type: 'gallery_approved',
    category: 'gallery',
    priority: 'info',
    title: '2 photos approved for live wall',
    message: 'Photos by Sophie Carter have been approved and are now on the live wall.',
    route: '/app/gallery?tab=media',
    routeLabel: 'View gallery',
    relatedType: 'gallery',
    relatedId: 'demo-gallery-approved',
    dedupKey: 'gallery-approved-sophie',
    readAt: new Date(Date.now() - 3600000 * 6).toISOString(),
    createdAt: new Date(Date.now() - 3600000 * 10).toISOString(),
    expiresAt: null,
    actorName: 'You',
    weddingName: WNAME,
  },
  {
    id: 'demo-notif-11',
    weddingId: W,
    type: 'event_updated',
    category: 'schedule',
    priority: 'info',
    title: 'Ceremony time changed',
    message: 'The ceremony has been moved from 2:00 PM to 1:30 PM.',
    route: '/app/schedule',
    routeLabel: 'View schedule',
    relatedType: 'event',
    relatedId: 'demo-event-ceremony',
    dedupKey: 'event-update-ceremony-time',
    readAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    expiresAt: null,
    actorName: 'James',
    weddingName: WNAME,
  },
  {
    id: 'demo-notif-12',
    weddingId: W,
    type: 'gallery_rejected',
    category: 'gallery',
    priority: 'info',
    title: '1 photo rejected',
    message: 'A photo by Amelia Wood was rejected — low resolution.',
    route: '/app/gallery?tab=moderation',
    routeLabel: 'View gallery',
    relatedType: 'gallery',
    relatedId: 'demo-gallery-rejected',
    dedupKey: 'gallery-rejected-amelia',
    readAt: new Date(Date.now() - 3600000 * 3).toISOString(),
    createdAt: new Date(Date.now() - 3600000 * 7).toISOString(),
    expiresAt: null,
    actorName: 'You',
    weddingName: WNAME,
  },
  {
    id: 'demo-notif-13',
    weddingId: W,
    type: 'registry_contribution',
    category: 'registry',
    priority: 'info',
    title: 'New contribution: Honeymoon fund (£150)',
    message: 'Anonymous contribution received toward your honeymoon fund.',
    route: '/app/budget/gift-funding',
    routeLabel: 'View funds',
    relatedType: 'fund',
    relatedId: 'demo-fund-honeymoon',
    dedupKey: 'registry-honeymoon-150',
    readAt: null,
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    expiresAt: null,
    actorName: 'Anonymous',
    weddingName: WNAME,
  },
  {
    id: 'demo-notif-14',
    weddingId: W,
    type: 'task_assigned',
    category: 'tasks',
    priority: 'info',
    title: 'New task: Finalise seating chart',
    message: 'Assigned to you by James — due 1 March.',
    route: '/app/tasks',
    routeLabel: 'View task',
    relatedType: 'task',
    relatedId: 'demo-task-seating',
    dedupKey: 'task-assigned-seating',
    readAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    expiresAt: null,
    actorName: 'James',
    weddingName: WNAME,
  },
  {
    id: 'demo-notif-15',
    weddingId: W,
    type: 'schedule_conflict',
    category: 'schedule',
    priority: 'action',
    title: 'Schedule conflict detected',
    message: 'Photographer appointment overlaps with the cake tasting.',
    route: '/app/calendar',
    routeLabel: 'View calendar',
    relatedType: 'conflict',
    relatedId: 'demo-conflict-photo-cake',
    dedupKey: 'conflict-photo-cake',
    readAt: null,
    createdAt: new Date(Date.now() - 3600000 * 1).toISOString(),
    expiresAt: null,
    actorName: 'System',
    weddingName: WNAME,
  },
];