import type { DemoInvitation, DemoInvitationRecipient, DemoInvitationTemplate } from './demoTypes';
import { DEMO_CONFIG } from './demoConfig';

const W = DEMO_CONFIG.weddingId;

export const demoInvitationTemplates: DemoInvitationTemplate[] = [
  {
    id: 'demo-tpl-classic',
    wedding_id: W,
    name: 'Classic Elegance',
    description: 'A timeless serif invitation with warm amber tones. Perfect for traditional church ceremonies and formal receptions.',
    template_type: 'standard',
    style_preset: 'classic',
    header_text: 'Together with their families',
    body_text: 'Emma Rose Hartley\n&\nJames Alexander Williams\n\nrequest the pleasure of your company\nat their wedding celebration\n\nSaturday, the fourteenth of June\ntwo thousand and twenty-seven\nat one o\'clock in the afternoon\n\nSt Mary\'s Church, Bathwick\nBath, Somerset',
    closing_text: 'Reception to follow\nat The Orangery, Royal Crescent\n\nDinner, drinks & dancing',
    footer_text: 'Kindly respond by the first of May 2027',
    rsvp_button_label: 'RSVP',
    is_default: true,
    status: 'active',
  },
  {
    id: 'demo-tpl-modern',
    wedding_id: W,
    name: 'Modern Minimal',
    description: 'Clean, contemporary sans-serif design with generous whitespace. Ideal for modern couples who want something understated.',
    template_type: 'standard',
    style_preset: 'modern',
    header_text: 'EMMA & JAMES',
    body_text: 'are getting married\n\n14 . 06 . 2027\n\nCeremony at 1pm\nSt Mary\'s Church, Bathwick\n\nReception from 3:30pm\nThe Orangery, Royal Crescent\n\nDinner, drinks and dancing to follow',
    closing_text: 'We can\'t wait to celebrate with you',
    footer_text: 'Please RSVP by 1st May 2027',
    rsvp_button_label: 'Respond',
    is_default: false,
    status: 'active',
  },
  {
    id: 'demo-tpl-botanical',
    wedding_id: W,
    name: 'Botanical Garden',
    description: 'Soft green hues with botanical-inspired styling. Beautiful for garden receptions and outdoor ceremonies.',
    template_type: 'standard',
    style_preset: 'botanical',
    header_text: 'Emma & James',
    body_text: 'Joyfully invite you to share\nin the beginning of their new life together\n\non Saturday, the fourteenth of June\ntwo thousand and twenty-seven\n\nCeremony at one o\'clock\nSt Mary\'s Church, Bathwick\n\nReception to follow at\nThe Orangery, Royal Crescent',
    closing_text: 'Dinner, drinks & dancing\nunder the summer sky',
    footer_text: 'Kindly RSVP by the first of May',
    rsvp_button_label: 'RSVP',
    is_default: false,
    status: 'active',
  },
  {
    id: 'demo-tpl-romantic',
    wedding_id: W,
    name: 'Romantic Blush',
    description: 'Delicate italic serif on soft rose — our most romantic template. Perfect for evening receptions and intimate celebrations.',
    template_type: 'standard',
    style_preset: 'romantic',
    header_text: 'Emma Rose & James Alexander',
    body_text: 'invite you to celebrate\ntheir wedding day\n\nSaturday, the fourteenth of June\nat one o\'clock in the afternoon\nSt Mary\'s Church, Bathwick\n\nFollowed by dinner and dancing\nat The Orangery, Royal Crescent',
    closing_text: 'With love and excitement,\nEmma & James',
    footer_text: 'Please RSVP by 1st May 2027',
    rsvp_button_label: 'Kindly Reply',
    is_default: false,
    status: 'active',
  },
  {
    id: 'demo-tpl-editorial',
    wedding_id: W,
    name: 'Editorial',
    description: 'Bold typography and confident layout. A statement template for couples who want their invitation to feel like a magazine spread.',
    template_type: 'standard',
    style_preset: 'editorial',
    header_text: 'EMMA HARTLEY\n&\nJAMES WILLIAMS',
    body_text: 'You are invited to celebrate our marriage\n\nSaturday 14 June 2027\n1:00pm\nSt Mary\'s Church · Bathwick\n\nCocktails, dinner & dancing\nfrom 3:30pm\nThe Orangery · Royal Crescent · Bath',
    closing_text: 'See you on the dance floor',
    footer_text: 'RSVP by 01.05.2027',
    rsvp_button_label: 'RSVP',
    is_default: false,
    status: 'active',
  },
];

export const demoInvitations: DemoInvitation[] = [
  { id: 'demo-inv-bennett', wedding_id: W, household_id: 'demo-hh-bennett', invitation_type: 'household', internal_name: 'Oliver Bennett — Best Man', formal_recipient_name: 'Mr Oliver Bennett & Miss Charlotte Ellis', informal_greeting: 'Oliver & Charlotte', delivery_method: 'email', language_code: 'en-GB', rsvp_deadline: '2027-02-28', status: 'ready', template_id: 'demo-tpl-classic' },
  { id: 'demo-inv-carter', wedding_id: W, household_id: 'demo-hh-carter', invitation_type: 'individual', internal_name: 'Sophie Carter — Maid of Honour', formal_recipient_name: 'Miss Sophie Carter', informal_greeting: 'Sophie', delivery_method: 'email', language_code: 'en-GB', rsvp_deadline: '2027-03-24', status: 'sent', template_id: 'demo-tpl-romantic' },
  { id: 'demo-inv-patel', wedding_id: W, household_id: 'demo-hh-patel', invitation_type: 'household', internal_name: 'Priya Patel & Family', formal_recipient_name: 'Dr Priya Patel, Mr Raj Patel & Family', informal_greeting: 'Priya, Raj & family', delivery_method: 'email', language_code: 'en-GB', rsvp_deadline: '2027-03-24', status: 'sent', template_id: 'demo-tpl-classic' },
  { id: 'demo-inv-bennett-sr', wedding_id: W, household_id: 'demo-hh-bennett-sr', invitation_type: 'couple', internal_name: 'Margaret & David Bennett', formal_recipient_name: 'Mrs Margaret Bennett & Mr David Bennett', informal_greeting: 'Mum & Dad', delivery_method: 'post', language_code: 'en-GB', rsvp_deadline: '2027-03-24', status: 'sent', template_id: 'demo-tpl-classic' },
  { id: 'demo-inv-carter-sr', wedding_id: W, household_id: 'demo-hh-carter-sr', invitation_type: 'couple', internal_name: 'Helen & Philip Carter', formal_recipient_name: 'Mrs Helen Carter & Mr Philip Carter', informal_greeting: 'Mum & Dad', delivery_method: 'email', language_code: 'en-GB', rsvp_deadline: '2027-03-24', status: 'sent', template_id: 'demo-tpl-botanical' },
  { id: 'demo-inv-wood', wedding_id: W, household_id: 'demo-hh-wood', invitation_type: 'individual', internal_name: 'Amelia Wood — Bridesmaid', formal_recipient_name: 'Miss Amelia Wood', informal_greeting: 'Amelia', delivery_method: 'email', language_code: 'en-GB', rsvp_deadline: '2027-03-24', status: 'sent', template_id: 'demo-tpl-modern' },
  { id: 'demo-inv-okonkwo', wedding_id: W, household_id: 'demo-hh-okonkwo', invitation_type: 'couple', internal_name: 'Ruth Okonkwo & Tom Davies', formal_recipient_name: 'Miss Ruth Okonkwo & Mr Tom Davies', informal_greeting: 'Ruth & Tom', delivery_method: 'email', language_code: 'en-GB', rsvp_deadline: '2027-03-24', status: 'sent', template_id: 'demo-tpl-editorial' },
  { id: 'demo-inv-whitfield', wedding_id: W, household_id: 'demo-hh-whitfield', invitation_type: 'individual', internal_name: 'George Whitfield — Groomsman', formal_recipient_name: 'Mr George Whitfield', informal_greeting: 'George', delivery_method: 'email', language_code: 'en-GB', rsvp_deadline: '2027-03-24', status: 'sent', template_id: 'demo-tpl-modern' },
  { id: 'demo-inv-chen', wedding_id: W, household_id: 'demo-hh-chen', invitation_type: 'individual', internal_name: 'Daniel Chen — Groomsman', formal_recipient_name: 'Mr Daniel Chen', informal_greeting: 'Daniel', delivery_method: 'email', language_code: 'en-GB', rsvp_deadline: '2027-03-24', status: 'sent', template_id: 'demo-tpl-modern' },
  { id: 'demo-inv-simmons', wedding_id: W, household_id: 'demo-hh-simmons', invitation_type: 'individual', internal_name: 'Laura Simmons', formal_recipient_name: 'Miss Laura Simmons', informal_greeting: 'Laura', delivery_method: 'email', language_code: 'en-GB', rsvp_deadline: '2027-03-24', status: 'sent', template_id: 'demo-tpl-botanical' },
  { id: 'demo-inv-walker', wedding_id: W, household_id: 'demo-hh-walker', invitation_type: 'individual', internal_name: 'James Walker', formal_recipient_name: 'Mr James Walker', informal_greeting: 'James', delivery_method: 'email', language_code: 'en-GB', rsvp_deadline: '2027-03-24', status: 'sent', template_id: 'demo-tpl-editorial' },
  { id: 'demo-inv-hussain', wedding_id: W, household_id: 'demo-hh-hussain', invitation_type: 'couple', internal_name: 'Nadia Hussain & Ahmed Khalil', formal_recipient_name: 'Dr Nadia Hussain & Mr Ahmed Khalil', informal_greeting: 'Nadia & Ahmed', delivery_method: 'email', language_code: 'en-GB', rsvp_deadline: '2027-03-24', status: 'sent', template_id: 'demo-tpl-romantic' },
  { id: 'demo-inv-carol', wedding_id: W, household_id: 'demo-hh-carol', invitation_type: 'individual', internal_name: 'Carol Bennett — Aunt', formal_recipient_name: 'Mrs Carol Bennett', informal_greeting: 'Aunt Carol', delivery_method: 'post', language_code: 'en-GB', rsvp_deadline: '2027-03-24', status: 'sent', template_id: 'demo-tpl-classic' },
  { id: 'demo-inv-thorne', wedding_id: W, household_id: 'demo-hh-thorne', invitation_type: 'individual', internal_name: 'Henry Thorne', formal_recipient_name: 'Mr Henry Thorne', informal_greeting: 'Henry', delivery_method: 'email', language_code: 'en-GB', rsvp_deadline: '2027-03-24', status: 'sent', template_id: 'demo-tpl-editorial' },
  { id: 'demo-inv-frost', wedding_id: W, household_id: 'demo-hh-frost', invitation_type: 'couple', internal_name: 'Eleanor & Robert Frost', formal_recipient_name: 'Mrs Eleanor Frost & Mr Robert Frost', informal_greeting: 'Eleanor & Robert', delivery_method: 'email', language_code: 'en-GB', rsvp_deadline: '2027-03-24', status: 'sent', template_id: 'demo-tpl-botanical' },
  { id: 'demo-inv-maya', wedding_id: W, household_id: 'demo-hh-maya', invitation_type: 'individual', internal_name: 'Maya Okonkwo — Evening', formal_recipient_name: 'Miss Maya Okonkwo', informal_greeting: 'Maya', delivery_method: 'email', language_code: 'en-GB', rsvp_deadline: '2027-02-28', status: 'draft', template_id: '' },
];

export const demoInvitationRecipients: DemoInvitationRecipient[] = [
  { id: 'demo-recip-bennett', wedding_id: W, invitation_id: 'demo-inv-bennett', guest_id: 'demo-guest-oliver', recipient_role: 'primary', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: true },
  { id: 'demo-recip-carter', wedding_id: W, invitation_id: 'demo-inv-carter', guest_id: 'demo-guest-sophie', recipient_role: 'primary', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: false },
  { id: 'demo-recip-patriya', wedding_id: W, invitation_id: 'demo-inv-patel', guest_id: 'demo-guest-priya', recipient_role: 'primary', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: false },
  { id: 'demo-recip-patraj', wedding_id: W, invitation_id: 'demo-inv-patel', guest_id: 'demo-guest-raj', recipient_role: 'partner', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: false },
  { id: 'demo-recip-patanika', wedding_id: W, invitation_id: 'demo-inv-patel', guest_id: 'demo-guest-anika', recipient_role: 'child', ceremony_included: true, reception_included: true, evening_included: false, plus_one_allowed: false },
  { id: 'demo-recip-patrohan', wedding_id: W, invitation_id: 'demo-inv-patel', guest_id: 'demo-guest-rohan', recipient_role: 'child', ceremony_included: true, reception_included: true, evening_included: false, plus_one_allowed: false },
  { id: 'demo-recip-margaret', wedding_id: W, invitation_id: 'demo-inv-bennett-sr', guest_id: 'demo-guest-margaret', recipient_role: 'primary', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: false },
  { id: 'demo-recip-david', wedding_id: W, invitation_id: 'demo-inv-bennett-sr', guest_id: 'demo-guest-david', recipient_role: 'partner', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: false },
  { id: 'demo-recip-helen', wedding_id: W, invitation_id: 'demo-inv-carter-sr', guest_id: 'demo-guest-helen', recipient_role: 'primary', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: false },
  { id: 'demo-recip-philip', wedding_id: W, invitation_id: 'demo-inv-carter-sr', guest_id: 'demo-guest-philip', recipient_role: 'partner', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: false },
  { id: 'demo-recip-amelia', wedding_id: W, invitation_id: 'demo-inv-wood', guest_id: 'demo-guest-amelia', recipient_role: 'primary', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: true },
  { id: 'demo-recip-ruth', wedding_id: W, invitation_id: 'demo-inv-okonkwo', guest_id: 'demo-guest-ruth', recipient_role: 'primary', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: false },
  { id: 'demo-recip-tom', wedding_id: W, invitation_id: 'demo-inv-okonkwo', guest_id: 'demo-guest-tom', recipient_role: 'partner', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: false },
  { id: 'demo-recip-george', wedding_id: W, invitation_id: 'demo-inv-whitfield', guest_id: 'demo-guest-george', recipient_role: 'primary', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: true },
  { id: 'demo-recip-daniel', wedding_id: W, invitation_id: 'demo-inv-chen', guest_id: 'demo-guest-daniel', recipient_role: 'primary', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: false },
  { id: 'demo-recip-laura', wedding_id: W, invitation_id: 'demo-inv-simmons', guest_id: 'demo-guest-laura', recipient_role: 'primary', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: true },
  { id: 'demo-recip-jamesw', wedding_id: W, invitation_id: 'demo-inv-walker', guest_id: 'demo-guest-james-w', recipient_role: 'primary', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: true },
  { id: 'demo-recip-nadia', wedding_id: W, invitation_id: 'demo-inv-hussain', guest_id: 'demo-guest-nadia', recipient_role: 'primary', ceremony_included: false, reception_included: true, evening_included: true, plus_one_allowed: false },
  { id: 'demo-recip-ahmed', wedding_id: W, invitation_id: 'demo-inv-hussain', guest_id: 'demo-guest-ahmed', recipient_role: 'partner', ceremony_included: false, reception_included: true, evening_included: true, plus_one_allowed: false },
  { id: 'demo-recip-carol', wedding_id: W, invitation_id: 'demo-inv-carol', guest_id: 'demo-guest-aunt-carol', recipient_role: 'primary', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: false },
  { id: 'demo-recip-henry', wedding_id: W, invitation_id: 'demo-inv-thorne', guest_id: 'demo-guest-henry', recipient_role: 'primary', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: true },
  { id: 'demo-recip-eleanor', wedding_id: W, invitation_id: 'demo-inv-frost', guest_id: 'demo-guest-eleanor', recipient_role: 'primary', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: false },
  { id: 'demo-recip-robert', wedding_id: W, invitation_id: 'demo-inv-frost', guest_id: 'demo-guest-robert', recipient_role: 'partner', ceremony_included: true, reception_included: true, evening_included: true, plus_one_allowed: false },
  { id: 'demo-recip-maya', wedding_id: W, invitation_id: 'demo-inv-maya', guest_id: 'demo-guest-maya', recipient_role: 'primary', ceremony_included: false, reception_included: false, evening_included: true, plus_one_allowed: false },
];