import type { DemoWedding, DemoWeddingVenue, DemoWeddingEvent } from './demoTypes';
import { DEMO_CONFIG } from './demoConfig';

export const demoWedding: DemoWedding = {
  id: DEMO_CONFIG.weddingId,
  title: 'Emma & James',
  partner_one_name: 'Emma',
  partner_two_name: 'James',
  wedding_date: '2027-04-24',
  date_confirmed: true,
  timezone: 'Europe/London',
  status: 'active',
  slug: DEMO_CONFIG.publicSlug,
  location: 'Bath, Somerset',
  welcome_message: 'We are so excited to celebrate our special day with you. Thank you for being part of our journey — we cannot wait to see you in Bath!',
  dress_code: 'Formal — black tie optional. Ladies, think spring garden party elegance. Gentlemen, suits or tuxedos. The Orangery can be warm in April, so layers are your friend.',
  contact_information: 'If you have any questions, please contact us at emma.and.james@example.com or call Sophie (Maid of Honour) on 07700 900123.',
  parking_notes: 'Limited parking is available at St Mary\'s Church. For the reception, The Orangery has a private car park with 40 spaces. Additional on-street parking is available on Great Pulteney Street. We recommend taxis or the Park & Ride from Odd Down.',
  accessibility_notes: 'St Mary\'s Church has step-free access via the north entrance. The Orangery is fully wheelchair accessible with disabled lavatories on the ground floor. If you have specific accessibility requirements, please let us know on your RSVP.',
  children_policy: 'Children are welcome at the ceremony and reception. We have arranged a supervised children\'s corner with activities during the wedding breakfast. Please indicate on your RSVP if your children will be attending so we can plan accordingly.',
  plus_one_policy: 'Named plus-ones are included on your invitation. If your invitation includes a plus-one, you will see their name on your RSVP form. Please contact us if you have any questions.',
  hashtag: '#EmmaAndJames2027',
};

export const demoVenues: DemoWeddingVenue[] = [
  {
    id: 'demo-venue-stmarys',
    wedding_id: DEMO_CONFIG.weddingId,
    venue_type: 'ceremony',
    name: 'St Mary\'s Church',
    address_line_1: 'Darlington Street',
    city: 'Bath',
    county_or_region: 'Somerset',
    postcode: 'BA2 6EB',
    country: 'United Kingdom',
    is_public: true,
  },
  {
    id: 'demo-venue-orangery',
    wedding_id: DEMO_CONFIG.weddingId,
    venue_type: 'reception',
    name: 'The Orangery',
    address_line_1: 'Great Pulteney Street',
    city: 'Bath',
    county_or_region: 'Somerset',
    postcode: 'BA2 4DB',
    country: 'United Kingdom',
    is_public: true,
  },
];

export const demoEvents: DemoWeddingEvent[] = [
  {
    id: 'demo-event-ceremony',
    wedding_id: DEMO_CONFIG.weddingId,
    event_type: 'ceremony',
    name: 'Wedding Ceremony',
    start_at: '2027-04-24T13:00:00+01:00',
    end_at: '2027-04-24T14:00:00+01:00',
    venue_id: 'demo-venue-stmarys',
    dress_code: 'Formal',
    description: 'The wedding ceremony will take place at the beautiful St Mary\'s Church in Bathwick. Please arrive by 12:30 to be seated before the bride arrives.',
    is_public: true,
    sort_order: 1,
  },
  {
    id: 'demo-event-reception',
    wedding_id: DEMO_CONFIG.weddingId,
    event_type: 'reception',
    name: 'Wedding Breakfast & Reception',
    start_at: '2027-04-24T15:00:00+01:00',
    end_at: '2027-04-25T00:00:00+01:00',
    venue_id: 'demo-venue-orangery',
    dress_code: 'Formal — black tie optional',
    description: 'Join us at The Orangery for a champagne reception, three-course wedding breakfast, speeches, and an evening of dancing with live music from The Night Owls Band.',
    is_public: true,
    sort_order: 2,
  },
  {
    id: 'demo-event-welcome',
    wedding_id: DEMO_CONFIG.weddingId,
    event_type: 'welcome',
    name: 'Welcome Drinks',
    start_at: '2027-04-23T19:00:00+01:00',
    end_at: '2027-04-23T21:30:00+01:00',
    venue_id: '',
    dress_code: 'Smart casual',
    description: 'For guests arriving on Friday evening, join us for welcome drinks at The Marlborough Tavern. A chance to catch up before the big day!',
    is_public: true,
    sort_order: 0,
  },
  {
    id: 'demo-event-farewell',
    wedding_id: DEMO_CONFIG.weddingId,
    event_type: 'farewell',
    name: 'Farewell Brunch',
    start_at: '2027-04-25T10:30:00+01:00',
    end_at: '2027-04-25T13:00:00+01:00',
    venue_id: 'demo-venue-orangery',
    dress_code: 'Casual',
    description: 'A relaxed brunch at The Orangery before everyone heads home. Drop in any time — we would love to say goodbye properly.',
    is_public: true,
    sort_order: 3,
  },
];